### ISSUE TITLE
[Feature Request] Option to hide Global Reports and Utilities

### ISSUE THREAD

**Issue by SemperRoto** [Wintermute0110/plugin.program.AEL#100]
I prefer to only have my launchers shown when I start AEL. It is already possible to hide special Categories/Launchers like Favorites, Rom Collections and so on. It would be a nice if you could hide the new Global Reports and Utilities from the Launcher Menu too. Personally I think they would fit better into the settings menu anyway but a hide function should be easier implemented and allow for the same result.

**Comment by joaosagrath** [comment]
+1 Me too!

**Comment by Wintermute0110** [comment]
Fixed. I'm closing the issue now.

There are technical reasons to move the Utilities and Global Report from the setting to the root window. I can elaborate if interested.
