### ISSUE TITLE
Exception when scraping ROM list with TheGamesGB on 0.9.8

### ISSUE THREAD

**Issue by remokeitel** [Wintermute0110/plugin.program.AEL#101]
Please see [hastebin](https://paste.kodi.tv/ulamomubag.kodi).
The exception is raised after the first ROM of a launcher ROM list.
Scraping single ROMs is working fine.

**Comment by Wintermute0110** [comment]
Should be fixed now. Please try. I will close the issue, if the error is still there reopen.
