### ISSUE TITLE
Export ROMs metadata to NFO files fails

### ISSUE THREAD

**Issue by mechevarria** [Wintermute0110/plugin.program.AEL#105]
In 0.9.8, attempting to export ROM metadata to NFO files errors out.

Steps:
AEL Launcher list -> Edit launcher -> Manage Roms -> Export ROMs metadata to NFO files

This is a link to the debug log. Problem seems to be around line 475
[https://pastebin.com/idqM3eun](https://pastebin.com/idqM3eun)

**Comment by Wintermute0110** [comment]
Thanks for reporting. I just fixed it with commit cdbe5da

**Comment by mechevarria** [comment]
Tried it out, everything is working, thanks! I grabbed a zip of the repo, but you might want to also do a 0.9.9 release since there are an additional 116 commits on the 0.9.8 branch since its release
