### ISSUE TITLE
TheGamesDB Scraper Broken

### ISSUE THREAD

**Issue by drinfernoo** [Wintermute0110/plugin.program.AEL#109]
Any game I attempt to scan in using TheGamesDB gives me the following error:

![image](https://user-images.githubusercontent.com/2319508/73108794-24c3c080-3eb6-11ea-9acf-3a0f5ec7da6c.png)

**Comment by Wintermute0110** [comment]
TheGamesDB is experiencing issues with the server, you can read the announcement [here](https://forums.thegamesdb.net/viewtopic.php?f=5&p=2228). In any case, they seem they are doing some changes in the API. I will check ASAP everything is all right on the AEL side.
