### ISSUE TITLE
LNK ROM launcher doesn't work with space in shortcut path

### ISSUE THREAD

**Issue by mmelvin0** [Wintermute0110/plugin.program.AEL#125]
This is because the argument start `start` wind up being double-quoted. This can be easily fixed by removing the double quotes around the {0} on this line (they belong in the `start` call above that for LNK applications though):

https://github.com/Wintermute0110/plugin.program.AEL/blob/9de17c646cc76e83600ec7b612d0356d95b1bfa4/resources/main.py#L8386

**Comment by Wintermute0110** [comment]
Thank you. I will have a look ASAP.

**Comment by Wintermute0110** [comment]
This should be fixed now. Please test and if it works close the issue.
