### ISSUE TITLE
"Scraper found no matching games" error

### ISSUE THREAD

**Issue by WarsTime** [Wintermute0110/plugin.program.AEL#133]
Hi
When I scrape a not found game with TheGamesDB in Py3 Version, I get this error :
`File "/home/server/.kodi/addons/plugin.program.advanced.emulator.launcher/resources/scrap.py",`
`line 1338, in _scrap_CM_get_candidate`
`    kodi_set_error_status('Scraper found no matching games')`
`TypeError: kodi_set_error_status() missing 1 required positional argument: 'msg'`

**Comment by Wintermute0110** [comment]
Fixed!
