### ISSUE TITLE
[Feature Request] Disable Kodi's internal screen blanker

### ISSUE THREAD

**Issue by Hybrid512** [Wintermute0110/plugin.program.AEL#145]
Hi,

I don't know if this is feasible or not but in Kodi, you can install many blanker addons with things like slideshows, videos, ...
These addons are handled by Kodi's own screen blanking events so I guess they can be enabled/disabled by asking Kodi to do so.

These blankers are not a problem by themselves for AEL since they don't appear while you're playing but, they run anyway and when you leave a game, you return to the running blanker and not to the Kodi UI.
Those blankers don't react to joypad events, only to mouse or keyboard events so unless you press a key, they don't go away.

I know you don't want to implement "platform specific code" as you said in #69 but this time, this is not to disable the system screen blanking but the internal Kodi's own screen blanker.

Would be great that each time a game is started, the blanker is disabled in Kodi then re-enabled once AEL gets the focus back.

Best regards.

**Comment by Wintermute0110** [comment]
That option already exists, go to AEL settings, tab Advanced. Note that this is only for the Kodi screensaver. #69 refers to external screensavers.

**Comment by Hybrid512** [comment]
Hi,

I saw that option but I thought I tried it and it didn't work but it was my mistake.
Works as expected so closing this ticket.
Thx
