### ISSUE TITLE
[Question] What is the purpose of the RetroArch System folder option?

### ISSUE THREAD

**Issue by amura11** [Wintermute0110/plugin.program.AEL#148]
I'm in the process of rebuilding my media PC and I noticed AEL has an option for the RetroArch System folder. I'm curious, if I set that what does that do? What folder is the system folder?

I couldn't find any documentation on this, if someone can give me a quick overview I'd be happy to write up some documentation myself.

**Comment by Wintermute0110** [comment]
Currently it is used by the command **Check Retroarch BIOSes** in the **Utilities** menu.

**Comment by amura11** [comment]
Cool, thanks for the answer!
