### ISSUE TITLE
Cant launch links from LNK launcher

### ISSUE THREAD

**Issue by andrew22224** [Wintermute0110/plugin.program.AEL#67]
I can set up a LNK launcher and perform a scan of my .lnk files which all show up fine as per this guide: https://forum.kodi.tv/showthread.php?tid=287826&pid=2606823#pid2606823

However when I launch a lnk file it gives me an error which I can't make sense 
For context my .lnk files are windows application shortcuts.

Here is my error log produced by simply logging into KODI and going straight to lnk to launch:

21:17:37.818 T:8028   ERROR: XFILE::CDirectory::GetDirectory - Error getting
21:17:39.265 T:8988   ERROR: Previous line repeats 2 times.
21:17:39.265 T:8988   ERROR: AEL DEBUG: ---------- Called AEL Main::run_plugin() constructor ----------
21:17:39.265 T:8988   ERROR: AEL DEBUG: sys.platform   "win32"
21:17:39.265 T:8988   ERROR: AEL DEBUG: Python version "2.7.13 (default, Jul 13 2017, 20:56:54) [MSC v.1900 32 bit (Intel)]"
21:17:39.265 T:8988   ERROR: AEL DEBUG: __a_version__  "0.9.9-alpha"
21:17:39.265 T:8988   ERROR: AEL DEBUG: sys.argv[0] "plugin://plugin.program.advanced.emulator.launcher/"
21:17:39.265 T:8988   ERROR: AEL DEBUG: sys.argv[1] "1"
21:17:39.265 T:8988   ERROR: AEL DEBUG: sys.argv[2] ""
21:17:39.265 T:8988   ERROR: AEL DEBUG: JSON      {"id" : 1, "jsonrpc" : "2.0", "method" : "Application.GetProperties", "params" : {"properties" : ["name", "version"]} }
21:17:39.265 T:8988   ERROR: AEL DEBUG: Response  {"id":1,"jsonrpc":"2.0","result":{"name":"Kodi","version":{"major":17,"minor":5,"revision":"20171023-5bd45ab","tag":"stable"}}}
21:17:39.265 T:8988   ERROR: AEL DEBUG: JSON      {"id" : 1, "jsonrpc" : "2.0", "method" : "Settings.GetSettingValue", "params" : {"setting" : "lookandfeel.skin"} }
21:17:39.265 T:8988   ERROR: AEL DEBUG: Response  {"id":1,"jsonrpc":"2.0","result":{"value":"skin.estuary"}}
21:17:39.265 T:8988   ERROR: AEL DEBUG: JSON RPC time 0.000 ms
21:17:39.275 T:8988   ERROR: AEL VERB : fs_load_catfile() Loading special://profile/addon_data\plugin.program.advanced.emulator.launcher\categories.xml
21:17:39.282 T:8988   ERROR: AEL DEBUG: command = "SHOW_ADDON_ROOT"
21:17:39.282 T:8988   ERROR: AEL DEBUG: Advanced Emulator Launcher run_concurrent() BEGIN
21:17:39.282 T:8988   ERROR: AEL DEBUG: _misc_set_AEL_Content() Setting Window(10000) property "AEL_Content" = "launchers"
21:17:39.414 T:8988   ERROR: AEL DEBUG: Advanced Emulator Launcher run_concurrent() END
21:17:39.414 T:8988   ERROR: AEL DEBUG: Advanced Emulator Launcher run_plugin() exit
21:17:43.431 T:7228   ERROR: AEL DEBUG: ---------- Called AEL Main::run_plugin() constructor ----------
21:17:43.431 T:7228   ERROR: AEL DEBUG: sys.platform   "win32"
21:17:43.432 T:7228   ERROR: AEL DEBUG: Python version "2.7.13 (default, Jul 13 2017, 20:56:54) [MSC v.1900 32 bit (Intel)]"
21:17:43.432 T:7228   ERROR: AEL DEBUG: __a_version__  "0.9.9-alpha"
21:17:43.432 T:7228   ERROR: AEL DEBUG: sys.argv[0] "plugin://plugin.program.advanced.emulator.launcher/"
21:17:43.432 T:7228   ERROR: AEL DEBUG: sys.argv[1] "2"
21:17:43.432 T:7228   ERROR: AEL DEBUG: sys.argv[2] "?catID=root_category&com=SHOW_ROMS&launID=12bf9d8b47042d1f4b4c1149f551a426"
21:17:43.432 T:7228   ERROR: AEL DEBUG: JSON      {"id" : 1, "jsonrpc" : "2.0", "method" : "Application.GetProperties", "params" : {"properties" : ["name", "version"]} }
21:17:43.432 T:7228   ERROR: AEL DEBUG: Response  {"id":1,"jsonrpc":"2.0","result":{"name":"Kodi","version":{"major":17,"minor":5,"revision":"20171023-5bd45ab","tag":"stable"}}}
21:17:43.432 T:7228   ERROR: AEL DEBUG: JSON      {"id" : 1, "jsonrpc" : "2.0", "method" : "Settings.GetSettingValue", "params" : {"setting" : "lookandfeel.skin"} }
21:17:43.432 T:7228   ERROR: AEL DEBUG: Response  {"id":1,"jsonrpc":"2.0","result":{"value":"skin.estuary"}}
21:17:43.432 T:7228   ERROR: AEL DEBUG: JSON RPC time 0.000 ms
21:17:43.441 T:7228   ERROR: AEL VERB : fs_load_catfile() Loading special://profile/addon_data\plugin.program.advanced.emulator.launcher\categories.xml
21:17:43.449 T:7228   ERROR: AEL DEBUG: command = "SHOW_ROMS"
21:17:43.449 T:7228   ERROR: AEL DEBUG: Advanced Emulator Launcher run_concurrent() BEGIN
21:17:43.449 T:7228   ERROR: AEL DEBUG: _misc_set_AEL_Content() Setting Window(10000) property "AEL_Content" = "roms"
21:17:43.449 T:7228   ERROR: AEL DEBUG: romsetfactory.create(): categoryID=root_category
21:17:43.449 T:7228   ERROR: AEL DEBUG: romsetfactory.create(): launcherID=12bf9d8b47042d1f4b4c1149f551a426
21:17:43.449 T:7228   ERROR: AEL INFO : RomSetFactory() loading standard romset...
21:17:43.449 T:7228   ERROR: AEL INFO : StandardRomSet() Loading ROMs in Launcher ...
21:17:43.449 T:7228   ERROR: AEL VERB : StandardRomSet.loadRoms() FILE  special://profile/addon_data\plugin.program.advanced.emulator.launcher\db_ROMs\roms_root_category_Test_12bf9d.json
21:17:43.449 T:7228   ERROR: AEL DEBUG: romsetfactory.create(): categoryID=vcat_pclone
21:17:43.449 T:7228   ERROR: AEL DEBUG: romsetfactory.create(): launcherID=12bf9d8b47042d1f4b4c1149f551a426
21:17:43.449 T:7228   ERROR: AEL INFO : RomSetFactory() loading standard romset...
21:17:43.450 T:7228   ERROR: AEL INFO : StandardRomSet() Loading ROMs in Launcher ...
21:17:43.450 T:7228   ERROR: AEL VERB : StandardRomSet.loadRoms() FILE  special://profile/addon_data\plugin.program.advanced.emulator.launcher\db_ROMs\roms_root_category_Test_12bf9d.json
21:17:43.450 T:7228   ERROR: AEL VERB : fs_load_Favourites_JSON() File special://profile/addon_data\plugin.program.advanced.emulator.launcher\favourites.json
21:17:43.616 T:7228   ERROR: AEL DEBUG: Loading seconds   0.00100016593933
21:17:43.616 T:7228   ERROR: AEL DEBUG: Rendering seconds 0.165999889374
21:17:43.616 T:7228   ERROR: AEL DEBUG: Advanced Emulator Launcher run_concurrent() END
21:17:43.616 T:7228   ERROR: AEL DEBUG: Advanced Emulator Launcher run_plugin() exit
21:17:45.134 T:5444   ERROR: AEL DEBUG: ---------- Called AEL Main::run_plugin() constructor ----------
21:17:45.134 T:5444   ERROR: AEL DEBUG: sys.platform   "win32"
21:17:45.134 T:5444   ERROR: AEL DEBUG: Python version "2.7.13 (default, Jul 13 2017, 20:56:54) [MSC v.1900 32 bit (Intel)]"
21:17:45.134 T:5444   ERROR: AEL DEBUG: __a_version__  "0.9.9-alpha"
21:17:45.134 T:5444   ERROR: AEL DEBUG: sys.argv[0] "plugin://plugin.program.advanced.emulator.launcher/"
21:17:45.134 T:5444   ERROR: AEL DEBUG: sys.argv[1] "-1"
21:17:45.134 T:5444   ERROR: AEL DEBUG: sys.argv[2] "?com=LAUNCH_ROM&catID=root_category&launID=12bf9d8b47042d1f4b4c1149f551a426&romID=d32cbad1e269d0d73053f1396f955650"
21:17:45.135 T:5444   ERROR: AEL DEBUG: JSON      {"id" : 1, "jsonrpc" : "2.0", "method" : "Application.GetProperties", "params" : {"properties" : ["name", "version"]} }
21:17:45.135 T:5444   ERROR: AEL DEBUG: Response  {"id":1,"jsonrpc":"2.0","result":{"name":"Kodi","version":{"major":17,"minor":5,"revision":"20171023-5bd45ab","tag":"stable"}}}
21:17:45.135 T:5444   ERROR: AEL DEBUG: JSON      {"id" : 1, "jsonrpc" : "2.0", "method" : "Settings.GetSettingValue", "params" : {"setting" : "lookandfeel.skin"} }
21:17:45.135 T:5444   ERROR: AEL DEBUG: Response  {"id":1,"jsonrpc":"2.0","result":{"value":"skin.estuary"}}
21:17:45.135 T:5444   ERROR: AEL DEBUG: JSON RPC time 0.000 ms
21:17:45.144 T:5444   ERROR: AEL VERB : fs_load_catfile() Loading special://profile/addon_data\plugin.program.advanced.emulator.launcher\categories.xml
21:17:45.155 T:5444   ERROR: AEL DEBUG: command = "LAUNCH_ROM"
21:17:45.156 T:5444   ERROR: AEL DEBUG: SingleInstance::__enter__() Lock not in use. Setting lock
21:17:45.156 T:5444   ERROR: AEL DEBUG: Advanced Emulator Launcher run_protected() BEGIN
21:17:45.156 T:5444   ERROR: AEL INFO : _command_run_rom() Launching ROM in Launcher ...
21:17:45.156 T:5444   ERROR: AEL DEBUG: romsetfactory.create(): categoryID=root_category
21:17:45.156 T:5444   ERROR: AEL DEBUG: romsetfactory.create(): launcherID=12bf9d8b47042d1f4b4c1149f551a426
21:17:45.156 T:5444   ERROR: AEL INFO : RomSetFactory() loading standard romset...
21:17:45.156 T:5444   ERROR: AEL INFO : StandardRomSet() Loading ROMs in Launcher ...
21:17:45.156 T:5444   ERROR: AEL VERB : StandardRomSet.loadRoms() FILE  special://profile/addon_data\plugin.program.advanced.emulator.launcher\db_ROMs\roms_root_category_Test_12bf9d.json
21:17:46.677 T:5444   ERROR: AEL DEBUG: Advanced Emulator Launcher run_protected() END
21:17:46.677 T:5444   ERROR: AEL DEBUG: SingleInstance::__exit__() Releasing lock
21:17:46.677 T:5444   ERROR: AEL DEBUG: Advanced Emulator Launcher run_plugin() exit

**Comment by Wintermute0110** [comment]
Please use release 0.9.7 or install from Github from branch `release-0.9.8`. Do not use `master` now because it is undergoing a huge refactoring and it's unstable.
