### ISSUE TITLE
Kodi Leia Support? And Re-scrape!

### ISSUE THREAD

**Issue by UnluckyForSome** [Wintermute0110/plugin.program.AEL#72]
Hi Wintermute0110 - I just want to say keep up the good work, this addon is the most polished, functional and cleanest option around for launching emulator games through Kodi! I would hate to see it go dead!

I was just wondering if AEL will work in Kodi 18? I don't want to upgrade and then find out my favourite addon no longer works! :)

One other thing, I think it may have been requested before - but the ability to re-scrape large sets of ROMs together would be awesome. Currently if something is not quite right I have to delete all the ROMs and then re-add them to get them to scrape again.

Many thanks!

**Comment by joaosagrath** [comment]
@UnluckyForSome 

I'm using Kodi Leia, and all functions of the addon works normally. I hard believe that @Wintermute0110  will not let this amazing piece of software die.

**Comment by Wintermute0110** [comment]
Hi, as @joaosagrath  said, AEL should work with no issues in Leia. There has been no significant changes in the Python API between Krypton and Leia. If you start using Leia and AEL does something strange open a bug report or comment on the Kodi forum.

> the ability to re-scrape large sets of ROMs together would be awesome.

I'm working on it. Currently I am in an Advanced MAME Launcher development cycle. After some weeks I will start working on the next AEL version. There is a lot of cool stuff in AML (for example, Fanart generation from other pieces of artwork) that I have to port from AML into AEL for the next version. Also, chrisim has done a lot of work with a new set of launchers.

**Comment by Wintermute0110** [comment]
Scrapers are working again in 0.9.8-beta1.
