### ISSUE TITLE
TheGamesDB scraper broken

### ISSUE THREAD

**Issue by tjwoosta** [Wintermute0110/plugin.program.AEL#75]
It seems to scrape fine, but results with every downloaded image being an empty 0kb file

**Comment by Wintermute0110** [comment]
OK, will have a look ASAP.

**Comment by Turnspit1337** [comment]
As of now, TheGamesDB scraping is completely broken, most likely due to changes to their API - the homepage has been completely remade.

**Comment by Wintermute0110** [comment]
Thanks for reporting. I had a quick look at the new TheGamesDB and yes, the scraper needs an overhaul. I will do it ASAP.

**Comment by Wintermute0110** [comment]
TGDB scraper is fixed in 0.9.8-beta1
