### ISSUE TITLE
How to set up artwork

### ISSUE THREAD

**Issue by treymerkley** [Wintermute0110/plugin.program.AEL#78]
I'm just wondering if you could give a quick explanation on how to set up the artwork for ROMs and launchers. After you explain it I can flesh it out into a full guide and put it in the wiki.

**Comment by billywade** [comment]
Hey, don't sweat it. There's a reason you don't see a lot of activity on my account. Take your time.

**Comment by Wintermute0110** [comment]
@treymerkley Sorry for taking so long, I forgot completely about this issue. Still you need help or figured how artwork works in AEL already?

**Comment by treymerkley** [comment]
Oh I haven't touched this for a while, I found a different setup that works for me. Thanks though!
