### ISSUE TITLE
Kodi input not working after exiting launched application

### ISSUE THREAD

**Issue by acc3ssd** [Wintermute0110/plugin.program.AEL#91]
I've been trying to find a replacement for Advanced Launcher to run Retroarch from within Kodi. I've successfully got AEL to launch Retroarch, but after exiting the application, I'm no longer able to control Kodi using my remote or keyboard. I'm forced to use my game controller or the mouse to restart Kodi before it starts working again.

I tried disabling the controller within Kodi, thinking that it might be taking over from the remote, but that didn't solve the problem. I'm running Kodi 18 on Ubuntu 18.04. I have the display manager set to automatically launch Kodi on boot (i.e., no window manager). Any idea how to fix this?

**Comment by Wintermute0110** [comment]
Yes. You need a window manager to run Kodi for AEL to work well. I recommend OpenBox. If you need help configuring OpenBox write here and I will post my Linux box configuration.

I will close the issue now cos is not really an AEL bug.

**Comment by acc3ssd** [comment]
Thanks for the response. Would you mind posting instructions on setting it up with OpenBox?
